using System.ComponentModel.DataAnnotations;

namespace E_Commerce.ViewModels
{
    public class CreateCategoryViewModel
    {
        // id is not needed for creation, as it will be generated by the database
        [Required]
        public string Name { get; set; }

        public string Description { get; set; }
    }
}
